/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package roquiclientsri;

import dev.joguenco.Main;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class MainTest {
    @Test void appHasAGreeting() {

        assertNotNull(new Main().getGreeting(), "app should have a greeting");
    }
}
