package autorizacion.ws.sri.gob.ec;
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
import java.util.logging.Logger;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-05-20T10:34:55.200-05:00
 * Generated source version: 3.5.5
 *
 */

@jakarta.jws.WebService(
                      serviceName = "AutorizacionComprobantesOfflineService",
                      portName = "AutorizacionComprobantesOfflinePort",
                      targetNamespace = "http://ec.gob.sri.ws.autorizacion",
                      wsdlLocation = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl",
                      endpointInterface = "autorizacion.ws.sri.gob.ec.AutorizacionComprobantesOffline")

public class AutorizacionComprobantesOfflinePortImpl implements AutorizacionComprobantesOffline {

    private static final Logger LOG = Logger.getLogger(AutorizacionComprobantesOfflinePortImpl.class.getName());

    /* (non-Javadoc)
     * @see autorizacion.ws.sri.gob.ec.AutorizacionComprobantesOffline#autorizacionComprobante(java.lang.String claveAccesoComprobante)*
     */
    public autorizacion.ws.sri.gob.ec.RespuestaComprobante autorizacionComprobante(java.lang.String claveAccesoComprobante) {
        LOG.info("Executing operation autorizacionComprobante");
        System.out.println(claveAccesoComprobante);
        try {
            autorizacion.ws.sri.gob.ec.RespuestaComprobante _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see autorizacion.ws.sri.gob.ec.AutorizacionComprobantesOffline#autorizacionComprobanteLote(java.lang.String claveAccesoLote)*
     */
    public autorizacion.ws.sri.gob.ec.RespuestaLote autorizacionComprobanteLote(java.lang.String claveAccesoLote) {
        LOG.info("Executing operation autorizacionComprobanteLote");
        System.out.println(claveAccesoLote);
        try {
            autorizacion.ws.sri.gob.ec.RespuestaLote _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
}
