package autorizacion.ws.sri.gob.ec;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-05-20T10:34:55.207-05:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://ec.gob.sri.ws.autorizacion", name = "AutorizacionComprobantesOffline")
@XmlSeeAlso({ObjectFactory.class})
public interface AutorizacionComprobantesOffline {

    @WebMethod
    @RequestWrapper(localName = "autorizacionComprobante", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "autorizacion.ws.sri.gob.ec.AutorizacionComprobante")
    @ResponseWrapper(localName = "autorizacionComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "autorizacion.ws.sri.gob.ec.AutorizacionComprobanteResponse")
    @WebResult(name = "RespuestaAutorizacionComprobante", targetNamespace = "")
    public autorizacion.ws.sri.gob.ec.RespuestaComprobante autorizacionComprobante(

        @WebParam(name = "claveAccesoComprobante", targetNamespace = "")
        java.lang.String claveAccesoComprobante
    );

    @WebMethod
    @RequestWrapper(localName = "autorizacionComprobanteLote", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "autorizacion.ws.sri.gob.ec.AutorizacionComprobanteLote")
    @ResponseWrapper(localName = "autorizacionComprobanteLoteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "autorizacion.ws.sri.gob.ec.AutorizacionComprobanteLoteResponse")
    @WebResult(name = "RespuestaAutorizacionLote", targetNamespace = "")
    public autorizacion.ws.sri.gob.ec.RespuestaLote autorizacionComprobanteLote(

        @WebParam(name = "claveAccesoLote", targetNamespace = "")
        java.lang.String claveAccesoLote
    );
}