package autorizacion.ws.sri.gob.ec;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-05-20T10:34:55.188-05:00
 * Generated source version: 3.5.5
 *
 */
public final class AutorizacionComprobantesOffline_AutorizacionComprobantesOfflinePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ec.gob.sri.ws.autorizacion", "AutorizacionComprobantesOfflineService");

    private AutorizacionComprobantesOffline_AutorizacionComprobantesOfflinePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AutorizacionComprobantesOfflineService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AutorizacionComprobantesOfflineService ss = new AutorizacionComprobantesOfflineService(wsdlURL, SERVICE_NAME);
        AutorizacionComprobantesOffline port = ss.getAutorizacionComprobantesOfflinePort();

        {
        System.out.println("Invoking autorizacionComprobante...");
        java.lang.String _autorizacionComprobante_claveAccesoComprobante = "";
        autorizacion.ws.sri.gob.ec.RespuestaComprobante _autorizacionComprobante__return = port.autorizacionComprobante(_autorizacionComprobante_claveAccesoComprobante);
        System.out.println("autorizacionComprobante.result=" + _autorizacionComprobante__return);


        }
        {
        System.out.println("Invoking autorizacionComprobanteLote...");
        java.lang.String _autorizacionComprobanteLote_claveAccesoLote = "";
        autorizacion.ws.sri.gob.ec.RespuestaLote _autorizacionComprobanteLote__return = port.autorizacionComprobanteLote(_autorizacionComprobanteLote_claveAccesoLote);
        System.out.println("autorizacionComprobanteLote.result=" + _autorizacionComprobanteLote__return);


        }

        System.exit(0);
    }
}
