package recepcion.ws.sri.gob.ec;
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
import java.util.logging.Logger;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-05-20T10:35:42.840-05:00
 * Generated source version: 3.5.5
 *
 */

@jakarta.jws.WebService(
                      serviceName = "RecepcionComprobantesOfflineService",
                      portName = "RecepcionComprobantesOfflinePort",
                      targetNamespace = "http://ec.gob.sri.ws.recepcion",
                      wsdlLocation = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl",
                      endpointInterface = "recepcion.ws.sri.gob.ec.RecepcionComprobantesOffline")

public class RecepcionComprobantesOfflinePortImpl implements RecepcionComprobantesOffline {

    private static final Logger LOG = Logger.getLogger(RecepcionComprobantesOfflinePortImpl.class.getName());

    /* (non-Javadoc)
     * @see recepcion.ws.sri.gob.ec.RecepcionComprobantesOffline#validarComprobante(byte[] xml)*
     */
    public recepcion.ws.sri.gob.ec.RespuestaSolicitud validarComprobante(byte[] xml) {
        LOG.info("Executing operation validarComprobante");
        System.out.println(xml);
        try {
            recepcion.ws.sri.gob.ec.RespuestaSolicitud _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
}