package recepcion.ws.sri.gob.ec;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-05-20T10:35:42.846-05:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://ec.gob.sri.ws.recepcion", name = "RecepcionComprobantesOffline")
@XmlSeeAlso({ObjectFactory.class})
public interface RecepcionComprobantesOffline {

    @WebMethod
    @RequestWrapper(localName = "validarComprobante", targetNamespace = "http://ec.gob.sri.ws.recepcion", className = "recepcion.ws.sri.gob.ec.ValidarComprobante")
    @ResponseWrapper(localName = "validarComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.recepcion", className = "recepcion.ws.sri.gob.ec.ValidarComprobanteResponse")
    @WebResult(name = "RespuestaRecepcionComprobante", targetNamespace = "")
    public recepcion.ws.sri.gob.ec.RespuestaSolicitud validarComprobante(

        @WebParam(name = "xml", targetNamespace = "")
        byte[] xml
    );
}