package recepcion.ws.sri.gob.ec;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-05-20T10:35:42.828-05:00
 * Generated source version: 3.5.5
 *
 */
public final class RecepcionComprobantesOffline_RecepcionComprobantesOfflinePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ec.gob.sri.ws.recepcion", "RecepcionComprobantesOfflineService");

    private RecepcionComprobantesOffline_RecepcionComprobantesOfflinePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RecepcionComprobantesOfflineService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        RecepcionComprobantesOfflineService ss = new RecepcionComprobantesOfflineService(wsdlURL, SERVICE_NAME);
        RecepcionComprobantesOffline port = ss.getRecepcionComprobantesOfflinePort();

        {
        System.out.println("Invoking validarComprobante...");
        byte[] _validarComprobante_xml = new byte[0];
        recepcion.ws.sri.gob.ec.RespuestaSolicitud _validarComprobante__return = port.validarComprobante(_validarComprobante_xml);
        System.out.println("validarComprobante.result=" + _validarComprobante__return);


        }

        System.exit(0);
    }
}